services:
  collector:
    image: alpine:latest
    environment:
      - HOME=/home/user
      - UID=${UID}
      - GID=${GID}
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - TERM=screen-256color
      - OPEN_SHELL=${OPEN_SHELL}
    #user: "${UID}:${GID}"
    volumes:
      - ${PWD}/bundle/${ARCH_OS}:/home/user
      - ${PWD}/downloads/${ARCH_OS}:/opt/downloads
      - ${PWD}/scripts/${ARCH_OS}:/opt/scripts
      - ${PWD}/files/${ARCH_OS}:/opt/files
    working_dir: /home/user
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      apk add -U --no-cache git curl bash setpriv rsync yq
      apk add -U --no-cache ncurses # required for tput 
      apk add -U --no-cache neovim # neovim.io requires glibc
      apk add -U --no-cache btop
      apk add -U --no-cache build-base # alpine-sdk # build-essential
      #su ${UID} -c /opt/scripts/collector.sh
      setpriv --reuid=${UID} --regid=${GID} --clear-groups /opt/scripts/collector.sh
